# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4b8304bbc290ced849570b33fe9fe40fe8065df0217e00f5749c4011d4f1d1b0829e2beff64d9c2860bfdfc88322fb95f4af2ca1e783dd0e3dae834c5fd4ca2

test:
  secret_key_base: c0444414e61ce346fe215b90d55a3426d3a9d94e4c8f1b81f491f6fefe04f7b0a1c5da740638c7e4a44966a5c0a9755d1b24c8efda481c7abf1664eab8612d88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
